name: Build and Release

on:
  push:
    branches: [main]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Create version file
        run: echo "__version__ = 'v${{ github.run_number }}'" > version.py

      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole --name "pesquisa" file_indexer.py
        #run: pyinstaller --onedir --noconsole --name "pesquisa" file_indexer.py

      #- name: Archive build output
      #  run: |
      #    Compress-Archive -Path dist/pesquisa -DestinationPath dist/pesquisa-v${{ github.run_number }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.run_number }}"
          tag_name: "v${{ github.run_number }}"
        # files: dist/pesquisa-v${{ github.run_number }}.zip
          files: dist/pesquisa.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
